{
 "title": "GenAI client",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "GenAI operation (success and error), rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (error_type) (rate(gen_ai_client_operation_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "LLM client request rate {{error_type}}"
    }
   ]
  },
  {
   "title": "GenAI client token usage rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (gen_ai_token_type) (rate(gen_ai_client_token_usage_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GenAI client response duration, sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gen_ai_client_operation_duration_seconds_bucket{error_type=\"\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(gen_ai_client_operation_duration_seconds_bucket{error_type=\"\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gen_ai_client_operation_duration_seconds_bucket{error_type=\"\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "GenAI client token usage distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gen_ai_client_token_usage_bucket[$__rate_interval])) by (le, gen_ai_token_type))",
     "legendFormat": "p99 {{gen_ai_token_type}} token usage"
    }
   ]
  }
 ]
}