kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gpu-test
nodes:
  - role: control-plane
    image: kindest/node:v1.24.12@sha256:1e12918b8bc3d4253bc08f640a231bb0d3b2c5a9b28aa3f2ca1aee93e1e8db16
    gpus: true
    extraMounts:
      - hostPath: /root/kubecon-genai-2024
        containerPath: /data
    extraPortMappings:
    - containerPort: 8000
      hostPort: 8000
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 9090
      hostPort: 9090
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 3000
      hostPort: 3000
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 18888
      hostPort: 18888
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30900
      hostPort: 30900
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30901
      hostPort: 30901
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30902
      hostPort: 30902
      listenAddress: "0.0.0.0"
      protocol: TCP