receivers:
  otlp:
    protocols:
      http:
        endpoint: "otelcollector:4418"
      grpc:
        endpoint: "otelcollector:4417"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true

processors:
  batch:
  resourcedetection/docker:
    detectors: [env, docker]

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, resourcedetection/docker]
      exporters: [prometheus]
